<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Carbon;

class PengeluaranSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'nama_pengeluaran'  => 'Assault Rifle AK-103',
                'tanggal'           => '2025-03-03',
                'nominal'           => 82000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Assault Rifle HK416',
                'tanggal'           => '2025-03-04',
                'nominal'           => 90000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Submachine Gun UMP45',
                'tanggal'           => '2025-03-05',
                'nominal'           => 45000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Submachine Gun P90',
                'tanggal'           => '2025-03-06',
                'nominal'           => 58000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Pistol Glock 19 Gen5',
                'tanggal'           => '2025-03-07',
                'nominal'           => 18000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Pistol SIG Sauer P320',
                'tanggal'           => '2025-03-08',
                'nominal'           => 22000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Sniper Rifle AWM .338 Lapua',
                'tanggal'           => '2025-03-09',
                'nominal'           => 240000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Sniper Rifle Sako TRG-42',
                'tanggal'           => '2025-03-10',
                'nominal'           => 210000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Sniper Rifle CheyTac M200 Intervention',
                'tanggal'           => '2025-03-11',
                'nominal'           => 350000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Sniper Rifle Dragunov SVD',
                'tanggal'           => '2025-03-12',
                'nominal'           => 170000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Pembelian Assault Rifle M4A1',
                'tanggal'           => '2025-01-10',
                'nominal'           => 75000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Amunisi 5.56mm NATO',
                'tanggal'           => '2025-01-12',
                'nominal'           => 25000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Drone Recon MQ-9 Mini',
                'tanggal'           => '2025-01-15',
                'nominal'           => 150000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Maintenance Tank Leopard 2A7',
                'tanggal'           => '2025-01-20',
                'nominal'           => 300000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Pembelian Sniper Rifle Barrett M82',
                'tanggal'           => '2025-01-25',
                'nominal'           => 180000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Amunisi .50 BMG',
                'tanggal'           => '2025-01-26',
                'nominal'           => 48000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Night Vision Goggles GEN-4',
                'tanggal'           => '2025-01-28',
                'nominal'           => 65000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Armored Vehicle MRAP Cougar',
                'tanggal'           => '2025-02-01',
                'nominal'           => 950000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Submachine Gun MP7',
                'tanggal'           => '2025-02-05',
                'nominal'           => 60000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Amunisi 4.6×30mm',
                'tanggal'           => '2025-02-06',
                'nominal'           => 15000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Anti Tank Rocket AT4',
                'tanggal'           => '2025-02-10',
                'nominal'           => 70000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Servis Helikopter Black Hawk',
                'tanggal'           => '2025-02-12',
                'nominal'           => 550000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Sistem Radar Portable AN/TPS-80',
                'tanggal'           => '2025-02-14',
                'nominal'           => 1200000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Jeep Militer Humvee H1',
                'tanggal'           => '2025-02-16',
                'nominal'           => 350000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Kevlar Helmet MK7',
                'tanggal'           => '2025-02-18',
                'nominal'           => 20000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Tactical Vest Modular Carrier',
                'tanggal'           => '2025-02-20',
                'nominal'           => 35000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Combat Drone Bayraktar TB2 Mini',
                'tanggal'           => '2025-02-22',
                'nominal'           => 300000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Shotgun Taktis Benelli M4',
                'tanggal'           => '2025-02-24',
                'nominal'           => 45000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Granat Fragmentasi M67',
                'tanggal'           => '2025-02-26',
                'nominal'           => 20000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Perbaikan Radar Jarak Menengah',
                'tanggal'           => '2025-03-01',
                'nominal'           => 250000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'APV Bushmaster Protected Mobility',
                'tanggal'           => '2025-03-13',
                'nominal'           => 850000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'APC M113 Armored Carrier',
                'tanggal'           => '2025-03-14',
                'nominal'           => 680000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'MPV Toyota Hilux Military Spec',
                'tanggal'           => '2025-03-15',
                'nominal'           => 450000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'MPV Mitsubishi Triton Tactical',
                'tanggal'           => '2025-03-16',
                'nominal'           => 430000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Truck Angkut Personel MAN HX60',
                'tanggal'           => '2025-03-17',
                'nominal'           => 900000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Truck Angkut Logistik Mercedes Zetros',
                'tanggal'           => '2025-03-18',
                'nominal'           => 1200000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'APV RG-31 Nyala',
                'tanggal'           => '2025-03-19',
                'nominal'           => 780000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'APC BTR-80 Personnel Carrier',
                'tanggal'           => '2025-03-20',
                'nominal'           => 1020000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'MPV Ford Ranger Tactical',
                'tanggal'           => '2025-03-21',
                'nominal'           => 390000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Truck Angkut Militer DAF YA-4440',
                'tanggal'           => '2025-03-22',
                'nominal'           => 880000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Tank T-90MS',
                'tanggal'           => '2025-03-23',
                'nominal'           => 5600000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Tank M1A2 Abrams SEP v3',
                'tanggal'           => '2025-03-24',
                'nominal'           => 7800000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Tank Leopard 2A5',
                'tanggal'           => '2025-03-25',
                'nominal'           => 6000000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Tank K2 Black Panther',
                'tanggal'           => '2025-03-26',
                'nominal'           => 8500000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Tank Merkava Mk4',
                'tanggal'           => '2025-03-27',
                'nominal'           => 7200000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Ransum Tempur MRE Paket A',
                'tanggal'           => '2025-03-28',
                'nominal'           => 5000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Ransum Tempur MRE Paket B',
                'tanggal'           => '2025-03-29',
                'nominal'           => 5200000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Amunisi 7.62mm NATO',
                'tanggal'           => '2025-03-30',
                'nominal'           => 33000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Amunisi RPG-7 HEAT',
                'tanggal'           => '2025-03-31',
                'nominal'           => 150000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
            [
                'nama_pengeluaran'  => 'Amunisi Mortir 81mm',
                'tanggal'           => '2025-04-01',
                'nominal'           => 270000000,
                'verifikator'       => 'Admin Jawara',
                'created_at' => Carbon::now(),
                'updated_at' => Carbon::now(),
            ],
        ];

        DB::table('pengeluaran')->insert($data);
    }
}
